import React, { useState } from 'react';
import { 
  X, 
  Share2, 
  Clipboard, 
  Check, 
  Download, 
  FileText, 
  Code2, 
  Database,
  FolderArchive,
  GitBranch,
  Terminal,
  ExternalLink
} from 'lucide-react';
import { ReviewResponse } from '../types/review';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  review?: ReviewResponse | null;
  language: string;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  review,
  language,
}) => {
  const [activeFormat, setActiveFormat] = useState<'markdown' | 'json' | 'refactor' | 'github'>('github');
  const [copied, setCopied] = useState(false);
  const [copiedGit, setCopiedGit] = useState(false);

  if (!isOpen) return null;

  const gitCommands = `# 1. Extract the downloaded zip and enter the folder:
cd devpulse-code-review-studio

# 2. Initialize Git repository:
git init
git add .
git commit -m "feat: initial commit of DevPulse AI Code Review Studio"

# 3. Connect to your GitHub repository and push:
git remote add origin https://github.com/<your-username>/devpulse-code-review-studio.git
git branch -M main
git push -u origin main`;

  const generateMarkdownReport = (): string => {
    if (!review) return '# No review available';

    return `## 🛡️ DevPulse AI Code Review Committee Report

**PR Verdict:** \`${review.verdict}\` (Health Index: **${review.overallScore}/100**)  
**Executive Summary:** ${review.verdictReason}

---

### 📋 Committee Consensus
> "${review.consensusSummary}"

---

### 📊 Quality Vector Benchmark
- **Correctness & Logic:** ${review.metrics.correctness}%
- **Security & OWASP:** ${review.metrics.security}%
- **Performance & Concurrency:** ${review.metrics.performance}%
- **Maintainability & Architecture:** ${review.metrics.maintainability}%
- **Testability & Resilience:** ${review.metrics.testability}%

---

### 🔍 Identified Issues (${review.issues.length})

${review.issues
  .map(
    (issue, i) => `#### ${i + 1}. [${issue.severity}] ${issue.title} (Line ${issue.line})
- **Pillar:** \`${issue.pillar}\` | **Reviewer:** ${issue.reviewer}
- **Impact:** ${issue.description}
- **Recommended Fix:** ${issue.fixRecommendation}
${
  issue.suggestedCode
    ? `\`\`\`${language}
${issue.suggestedCode}
\`\`\``
    : ''
}`
  )
  .join('\n\n')}

---

### 🧪 Senior QA Test Matrix (${review.qaReview?.testPlan?.length || 0} Cases)
| Test Case | Category | Expected Behavior |
|:---|:---|:---|
${(review.qaReview?.testPlan || [])
  .map((tc) => `| ${tc.testCaseName} | \`${tc.testType}\` | ${tc.expectedResult} |`)
  .join('\n')}

---

### 🏗️ Engineering Manager Strategic Audit
- **Architectural Risks:** ${review.engManagerReview.architecturalRisks?.join('; ') || 'None'}
- **Security Posture:** ${review.engManagerReview.securityRisks?.join('; ') || 'None'}
- **Scalability Bottlenecks:** ${review.engManagerReview.scalabilityBottlenecks?.join('; ') || 'None'}
- **Tech Debt Assessment:** ${review.engManagerReview.techDebtAssessment}
- **Recommended Action:** ${review.engManagerReview.recommendedAction}

---
*Generated by DevPulse AI Code Review Studio (Senior SWE, QA & EM Simulation)*
`;
  };

  const getExportContent = () => {
    if (activeFormat === 'github') return gitCommands;
    if (!review) return '';
    if (activeFormat === 'markdown') return generateMarkdownReport();
    if (activeFormat === 'json') return JSON.stringify(review, null, 2);
    if (activeFormat === 'refactor') return review.refactoredCode;
    return '';
  };

  const content = getExportContent();

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyGit = async () => {
    await navigator.clipboard.writeText(gitCommands);
    setCopiedGit(true);
    setTimeout(() => setCopiedGit(false), 2000);
  };

  const handleDownloadZip = () => {
    window.location.href = '/api/download-zip';
  };

  const handleDownload = () => {
    if (activeFormat === 'github') {
      handleDownloadZip();
      return;
    }

    let filename = 'code_review_report.md';
    let mime = 'text/markdown';
    if (activeFormat === 'json') {
      filename = 'code_review_audit.json';
      mime = 'application/json';
    } else if (activeFormat === 'refactor') {
      const ext = language === 'python' ? 'py' : language === 'go' ? 'go' : 'ts';
      filename = `refactored_code.${ext}`;
      mime = 'text/plain';
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm select-none">
      <div className="bg-slate-900 border border-slate-700 rounded-2xl max-w-2xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
        {/* Header */}
        <div className="p-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Share2 className="w-4 h-4 text-indigo-400" />
            <h3 className="text-sm font-semibold text-slate-100">
              Export Project & Review Artifacts
            </h3>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded text-slate-400 hover:text-slate-200 hover:bg-slate-800"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selector Tabs */}
        <div className="px-4 pt-3 pb-2 bg-slate-950/60 border-b border-slate-800 flex items-center gap-1.5 text-xs overflow-x-auto">
          <button
            onClick={() => setActiveFormat('github')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md font-semibold transition-colors shrink-0 ${
              activeFormat === 'github'
                ? 'bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-sm'
                : 'text-slate-300 hover:text-white bg-slate-900 border border-slate-800'
            }`}
          >
            <FolderArchive className="w-3.5 h-3.5 text-emerald-300" />
            <span>GitHub Project (.zip)</span>
          </button>
          <button
            onClick={() => setActiveFormat('markdown')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md font-medium transition-colors shrink-0 ${
              activeFormat === 'markdown'
                ? 'bg-indigo-600 text-white'
                : 'text-slate-400 hover:text-slate-200 bg-slate-900'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span>PR Markdown</span>
          </button>
          <button
            onClick={() => setActiveFormat('json')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md font-medium transition-colors shrink-0 ${
              activeFormat === 'json'
                ? 'bg-indigo-600 text-white'
                : 'text-slate-400 hover:text-slate-200 bg-slate-900'
            }`}
          >
            <Database className="w-3.5 h-3.5" />
            <span>JSON Audit</span>
          </button>
          <button
            onClick={() => setActiveFormat('refactor')}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-md font-medium transition-colors shrink-0 ${
              activeFormat === 'refactor'
                ? 'bg-indigo-600 text-white'
                : 'text-slate-400 hover:text-slate-200 bg-slate-900'
            }`}
          >
            <Code2 className="w-3.5 h-3.5" />
            <span>Refactored Code</span>
          </button>
        </div>

        {/* Content Body */}
        <div className="flex-1 p-4 overflow-y-auto space-y-3">
          {activeFormat === 'github' ? (
            <div className="space-y-3.5 text-xs">
              <div className="p-4 rounded-xl bg-gradient-to-r from-emerald-950/40 via-slate-900 to-slate-900 border border-emerald-800/80 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <FolderArchive className="w-4 h-4 text-emerald-400" />
                    <span className="font-semibold text-slate-100 text-sm">
                      Ready-to-Push GitHub Repository Package (.zip)
                    </span>
                  </div>
                  <p className="text-slate-300 text-[11px] mt-1 leading-relaxed">
                    Includes all TypeScript components, Express backend with Gemini API proxy, preloaded samples, Electron wrapper, README.md, and package.json.
                  </p>
                </div>
                <button
                  onClick={handleDownloadZip}
                  className="px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-semibold text-xs shadow-md shadow-emerald-900/30 flex items-center gap-2 shrink-0 cursor-pointer"
                >
                  <Download className="w-4 h-4" />
                  <span>Download Project .zip</span>
                </button>
              </div>

              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="font-semibold text-slate-300 flex items-center gap-1.5 text-xs">
                    <GitBranch className="w-3.5 h-3.5 text-indigo-400" />
                    <span>How to push this project to GitHub:</span>
                  </span>
                  <button
                    onClick={handleCopyGit}
                    className="flex items-center gap-1 text-slate-400 hover:text-slate-200 text-[11px]"
                  >
                    {copiedGit ? (
                      <>
                        <Check className="w-3 h-3 text-emerald-400" />
                        <span className="text-emerald-400">Copied</span>
                      </>
                    ) : (
                      <>
                        <Clipboard className="w-3 h-3" />
                        <span>Copy Commands</span>
                      </>
                    )}
                  </button>
                </div>
                <pre className="p-3.5 bg-slate-950 border border-slate-800 rounded-lg text-slate-300 font-mono text-[11px] leading-relaxed overflow-x-auto">
                  <code>{gitCommands}</code>
                </pre>
              </div>

              <div className="p-3 rounded-lg bg-slate-950 border border-slate-800 text-[11px] text-slate-400 space-y-1">
                <span className="font-semibold text-slate-300 block">Files included in the zip:</span>
                <p className="font-mono text-[10px] text-slate-500">
                  README.md, LICENSE, package.json, server.ts, electron-main.cjs, index.html, vite.config.ts, tsconfig.json, .env.example, .gitignore, src/ (App.tsx, components/*, data/samples.ts, types/review.ts, index.css)
                </p>
              </div>
            </div>
          ) : (
            <pre className="p-3.5 bg-slate-950 border border-slate-800 rounded-lg text-slate-300 font-mono text-[11px] leading-relaxed overflow-x-auto whitespace-pre-wrap select-text">
              {content || '// No review data available to export yet.'}
            </pre>
          )}
        </div>

        {/* Footer */}
        <div className="p-3 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <span className="text-[11px] text-slate-500">
            {activeFormat === 'github' ? 'Complete project bundle ready' : `${content.length} characters ready to export`}
          </span>

          <div className="flex items-center gap-2">
            {activeFormat === 'github' ? (
              <button
                onClick={handleDownloadZip}
                className="px-4 py-1.5 rounded-md text-xs font-semibold bg-emerald-600 hover:bg-emerald-500 text-white flex items-center gap-1.5 transition-colors cursor-pointer"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .zip</span>
              </button>
            ) : (
              <>
                <button
                  onClick={handleDownload}
                  className="px-3 py-1.5 rounded-md text-xs text-slate-300 bg-slate-800 hover:bg-slate-750 flex items-center gap-1.5 transition-colors cursor-pointer"
                >
                  <Download className="w-3.5 h-3.5 text-slate-400" />
                  <span>Download File</span>
                </button>
                <button
                  onClick={handleCopy}
                  className="px-4 py-1.5 rounded-md text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white flex items-center gap-1.5 transition-colors cursor-pointer"
                >
                  {copied ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-300" />
                      <span>Copied!</span>
                    </>
                  ) : (
                    <>
                      <Clipboard className="w-3.5 h-3.5" />
                      <span>Copy to Clipboard</span>
                    </>
                  )}
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
